# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6f5101f55dd74c253fd96884cf56437f"
name = "section-hero"
handle = "section-hero-3"
application_url = "https://corpus-conditional-levy-mississippi.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "section-hero.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://corpus-conditional-levy-mississippi.trycloudflare.com/auth/callback",
  "https://corpus-conditional-levy-mississippi.trycloudflare.com/auth/shopify/callback",
  "https://corpus-conditional-levy-mississippi.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
